# The Docker image that will be used to build your app
image: node:16.17.1

pages:
  cache:
    paths:
      - node_modules/
  script:
    # Specify the steps involved to build your app here
    - npm install
    - npm run build
    - mkdir public
    - cp -r src/.vuepress/dist/* public/

  artifacts:
    paths:
    - public

  only:
    # Trigger a new build and deploy only when there is a push to the
    # branch(es) below
    - main
