# Define the stages of the pipeline
stages:
  - build
  - test
  - deploy

# Define the variables used in the pipeline
variables:
  IMAGE_NAME: registry.example.com/my-app/backend
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypassword
  POSTGRES_DB: mydb
  DOCKER_DRIVER: overlay2

# Define the jobs in the pipeline
# Build job: build the Docker image for the application
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME .

# Test job: run unit and integration tests
test:
  stage: test
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - python manage.py test

# Deploy job: deploy the application to a Kubernetes cluster
deploy:
  stage: deploy
  image: google/cloud-sdk:alpine
  script:
    - echo $GCLOUD_SERVICE_KEY > /tmp/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json
    - gcloud container clusters get-credentials my-cluster --zone us-central1-a --project my-project
    - kubectl apply -f deployment.yaml
  environment:
    name: production
    url: https://example.com
  only:
    - master

