name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Build Application
        run: |
          # insert build command here
          # example: npm run build
      
      - name: Test Application
        run: |
          # insert test command here
          # example: npm run test
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy Application
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.DEPLOY_USERNAME }}
          host: ${{ secrets.DEPLOY_HOST }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            # insert deployment commands here
            # example: scp -r ./dist/* user@host:/var/www/my-app/

