name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      env:
        ACCESS_TOKEN: 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
        TARGET_REPO: nazmul-devops/personal-docs-site
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm && npm run build
        BUILD_DIR: blog/.vuepress/dist/
